### ISSUE TITLE
Corvus.ContentHandling.Specs.csproj sets RootNamespace to Corvus.Extensions.Specs

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.ContentHandling#3]
Presumably this is a cut and paste error:

```xml
<RootNamespace>Corvus.Extensions.Specs</RootNamespace>
```

See https://github.com/corvus-dotnet/Corvus.ContentHandling/blob/master/Solutions/Corvus.ContentHandling.Specs/Corvus.ContentHandling.Specs.csproj#L7

**Comment by mwadams** [comment]
This appears to be fixed in master.
