### ISSUE TITLE
Support constructor-based deserialization

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.ContentHandling#96]
Currently, the deserialization model for `Corvus.ContentHandling` is property-based. The `ContentTypeConverter` works by first retrieving an instance of the target type from an `IServiceProvider`, and then calling `JsonSerializer.Populate` to deserialize JSON into the object's properties.

This is bad news for code that wants to enable C# 8's nullable reference features. Constructor-based initialization is very much the preferred approach there because it enables you to ensure that non-nullable properties are correctly initialized by construction. Without that, you end up either implementing the laborious pattern in which such properties are backed by a nullable field, throwing an exception if the field is null by the time the property is accessed, or alternatively we can just give up and disable nullable annotations for affected properties. e.g.:

https://github.com/marain-dotnet/Marain.TenantManagement/blob/8c2202d5ba00d1c1f8db5466bebe1418301a90d2/Solutions/Marain.TenantManagement.Abstractions/Marain/TenantManagement/ServiceManifests/ServiceManifestRequiredConfigurationEntry.cs#L32-L45 - 

```csharp
        /// <summary>
        /// Gets or sets the key of the configuration entry. This is used to match configuration supplied as part of
        /// enrollment with the configuration entry it relates to.
        /// </summary>
#nullable disable annotations
        public string Key { get; set; }
#nullable restore annotations

        /// <summary>
        /// Gets or sets the description of the configuration entry.
        /// </summary>
#nullable disable annotations
        public string Description { get; set; }
#nullable restore annotations
```

Json.NET supports constructor-based deserialization, so the main question here is: why does `Corvus.ContentHandling` not just defer entirely to Json.NET here? And the answer appears to be: to enable these types to use dependency injection.

This seems to me to be a questionable proposition. Types used with content handling are essentially plain old data. They are most often used as the in-memory representation of data that has been or will be serialized, either at an API boundary, or because it is being stored persistently. So why do such types need DI?

One answer is that in some cases we've painted ourselves into a corner by making some of our serializable types responsible for owning serialization settings. Take https://github.com/corvus-dotnet/Corvus.Extensions.Newtonsoft.Json/issues/86 for example—`PropertyBag` requires `JsonSerializerSettings`, and although it will construct its own defaults if you don't supply them that's often not what you want: if you're going to be storing the property bag somewhere you probably want to supply your own settings. And so it's often important that the `PropertyBag` be supplied with the right settings. This in turn means that types that use a `PropertyBag` such as [`ITenant`](https://github.com/corvus-dotnet/Corvus.Tenancy/blob/cb7590e2a9936b1a86c2d3510b8dc13a2ed43705/Solutions/Corvus.Tenancy.Abstractions/Corvus/Tenancy/ITenant.cs) also need to be supplied with a `JsonSerializerSettings` so as to be able to pass it on to the `PropertyBag`. So if you look at the [current implementation, `Tenant`](https://github.com/corvus-dotnet/Corvus.Tenancy/blob/cb7590e2a9936b1a86c2d3510b8dc13a2ed43705/Solutions/Corvus.Tenancy.Abstractions/Corvus/Tenancy/Tenant.cs) you can see its constructor requires an `IJsonSerializerSettingsProvider`.

So that implementation of `ITenant` depends on being constructed via DI in order to pick up the correct JSON serialization settings. That's why the content handling `ContentTypeConverter` does what it does: it asks DI for a new instance of the target type (`Tenant` in this case), thus ensuring that the correct settings get passed in, and then it fills in all the properties.

The proper solution in this particular example is almost certainly to remove any serialization-mechanism-specific behaviour from `Tenant`. Individual tenant objects should not really be in charge of deciding how to be serialized; that is a decision for the thing doing the serialization.

A bigger question, though, is what is the right approach in general: are there other scenarios for `Corvus.ContentHandler` deserialization in which we genuinely need the outputs to be initialized via DI? I'm not currently convinced that there should be any. So my current view is that `ContentTypeHandler` should be asking Json.NET to create the object for it, instead of using `JsonSerializer.Populate`.

But this would have a significant impact. The entire content type registration system as it currently stands is tightly coupled to presumptions about the relationship with DI. The change I'm suggesting would essentially remove that.

Alternatively, we could decide to support property-based deserialization _and_ DI-based target initialization. The primary merit of this is that it avoids having to think to hard about the current design... It would be a lot more work: we'd pretty much have to re-implement the constructor-based deserialization ourselves, along with a significant chunk of the DI resolution work that's currently done for us by the DI system. This is absolutely possible, but before embarking on this, I would want to know why we need types that essentially represent serializable content—plain old data, in essence—to be initialized with services obtained via DI.

**Comment by mwadams** [comment]
I see no problem with making this breaking change right now, if it can be done.

It would also be the point to move away from Json.NET as our primary serialization mechanism, and a move to `System.Text.Json` as the blocker for us is the lack of support for property-based initialization in the latter.

I'd really like to see how this plays out through the whole design, because I can't get my head around what the code will look like for the consumer, and how we prevent it becoming "something you have to think about" as the developer.

**Comment by idg10** [comment]
I suggest we use `ITenant` as the example to drive this through. This will mean also coming up with an answer to https://github.com/corvus-dotnet/Corvus.Extensions.Newtonsoft.Json/issues/86

Rather than discuss it endlessly, I think I'll choose an answer to that and create a draft PR for it, and then we can see whether I chose wrong.

**Comment by mwadams** [comment]
I agree. Yes please :)
